# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    async def FormFilling(self, task_steps: str,current_status: types.FormFillingStatus,current_browser_state: str,phone: str,aadhaar_number: str,aadhar_otp: typing.Optional[str],dob: str,relationship: str,pin_code: str,district: str,sub_district: str,village: str,area_type: str,family_id: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.FormFillingStatus:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="FormFilling", args={
            "task_steps": task_steps,"current_status": current_status,"current_browser_state": current_browser_state,"phone": phone,"aadhaar_number": aadhaar_number,"aadhar_otp": aadhar_otp,"dob": dob,"relationship": relationship,"pin_code": pin_code,"district": district,"sub_district": sub_district,"village": village,"area_type": area_type,"family_id": family_id,
        })
        return typing.cast(types.FormFillingStatus, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def FormFilling(self, task_steps: str,current_status: types.FormFillingStatus,current_browser_state: str,phone: str,aadhaar_number: str,aadhar_otp: typing.Optional[str],dob: str,relationship: str,pin_code: str,district: str,sub_district: str,village: str,area_type: str,family_id: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.FormFillingStatus, types.FormFillingStatus]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="FormFilling", args={
            "task_steps": task_steps,"current_status": current_status,"current_browser_state": current_browser_state,"phone": phone,"aadhaar_number": aadhaar_number,"aadhar_otp": aadhar_otp,"dob": dob,"relationship": relationship,"pin_code": pin_code,"district": district,"sub_district": sub_district,"village": village,"area_type": area_type,"family_id": family_id,
        })
        return baml_py.BamlStream[stream_types.FormFillingStatus, types.FormFillingStatus](
          result,
          lambda x: typing.cast(stream_types.FormFillingStatus, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.FormFillingStatus, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def FormFilling(self, task_steps: str,current_status: types.FormFillingStatus,current_browser_state: str,phone: str,aadhaar_number: str,aadhar_otp: typing.Optional[str],dob: str,relationship: str,pin_code: str,district: str,sub_district: str,village: str,area_type: str,family_id: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="FormFilling", args={
            "task_steps": task_steps,"current_status": current_status,"current_browser_state": current_browser_state,"phone": phone,"aadhaar_number": aadhaar_number,"aadhar_otp": aadhar_otp,"dob": dob,"relationship": relationship,"pin_code": pin_code,"district": district,"sub_district": sub_district,"village": village,"area_type": area_type,"family_id": family_id,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def FormFilling(self, task_steps: str,current_status: types.FormFillingStatus,current_browser_state: str,phone: str,aadhaar_number: str,aadhar_otp: typing.Optional[str],dob: str,relationship: str,pin_code: str,district: str,sub_district: str,village: str,area_type: str,family_id: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="FormFilling", args={
            "task_steps": task_steps,"current_status": current_status,"current_browser_state": current_browser_state,"phone": phone,"aadhaar_number": aadhaar_number,"aadhar_otp": aadhar_otp,"dob": dob,"relationship": relationship,"pin_code": pin_code,"district": district,"sub_district": sub_district,"village": village,"area_type": area_type,"family_id": family_id,
        }, mode="stream")
        return result
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))