# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (1)
# #########################################################################

class FormFillingStatus(BaseModel):
    step_index: typing.Optional[int] = None
    current_step_summary: typing.Optional[str] = None
    url: typing.Optional[str] = None
    awaiting_user_input: typing.Optional[bool] = None
    requested_input_type: typing.Optional[str] = None
    task_complete: typing.Optional[bool] = None
    error_message: typing.Optional[str] = None
    next_expected_action: typing.Optional[str] = None
    page_state: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
